apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: myname
  region: us-east-1

nodeGroups:
  - name: ng-1
    labels:  
      worker: default
    instanceType: t2.micro
    desiredCapacity: 1
    minSize: 2
    maxSize: 2
availabilityZones: ['us-east-1a', 'us-east-1b', 'us-east-1c', 'us-east-1d']
