apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume-green
spec:
  storageClassName: manual
  capacity:
    storage: 250Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/ravi_green"
